FinalTask/course_app/urls.py
from . import views
from django.urls import path
app_name='course_app'

urlpatterns = [

    path('cs',views.cs,name='cs'),
    path('comm',views.comm,name='comm'),
    path('bio',views.bio,name='bio'),
    path('BE',views.BE,name='BE'),
    path('diploma',views.diploma,name='diploma'),
]

FinalTask/final_app/urls.py
from . import views
from django.urls import path
app_name='final_app'

urlpatterns = [

    path('',views.index,name='index'),
]

FinalTask/finalproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('final_app.urls')),
    path('register/',include('index_app.urls')),
    path('course/',include('course_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FinalTask/index_app/urls.py
from . import views
from django.urls import path
app_name='index_app'


urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('form',views.form,name='form')
]

FinalTask/course_app/models.py
from django.db import models

# Create your models here.

FinalTask/final_app/models.py
from django.db import models

# Create your models here.

FinalTask/index_app/models.py
from django.db import models

# Create your models here.

FinalTask/course_app/views.py
from django.shortcuts import render

# Create your views here.
def cs(request):
    return render(request,'cs.html')
def comm(request):
    return render(request,'com.html')
def bio(request):
    return render(request,'bio.html')
def BE(request):
    return render(request,'BE.html')
def diploma(request):
    return render(request,'diploma.html')

FinalTask/final_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request,'index2.html')

FinalTask/index_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid validations')
            return redirect('index_app:login')
    return render(request, 'loginpage.html')



def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if cpassword == password:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken")
                return redirect('index_app:register')
            else:
                 user = User.objects.create_user(username=username, password=password)
                 user.save()
                 return redirect('index_app:login')
        else:
             messages.info(request,"password not match")
             return redirect('index_app:register')
        return redirect('/')
    return render(request,'registerpage.html')
def logout(request):
    auth.logout(request)
    return redirect('/')
def form(request):
    return render(request,'register form.html')

FinalTask/templates/BE.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BE</title>
</head>
<body>
{% block content %}
    <div class="container-xxl py-5 category">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Categories</h6>
                <h1 class="mb-5">BE DEPARTMENT</h1>
            </div>
            <div class="row g-3">
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/be1.webp' %}" alt="">

                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/be2.jpg' %}" alt="">

                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/be3.webp' %}" alt="">

                            </a>
                        </div>
                    </div>
                </div>

                <a href="{% url 'index_app:form' %}" class="btn btn-primary-center">Register Form</a>
                {% endblock %}
</body>
</html>

FinalTask/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>LEARNING-COURSES</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="stylesheet">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>BASE</title>
</head>
<body>

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="{% url 'final_app:index' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>LEARNING COURSES</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url 'final_app:index' %}" class="nav-item nav-link active">Home</a>
                {% if user.is_authenticated %}
                  Hello {{user.username}}
                <a href="{% url 'index_app:logout' %}" class="nav-item nav-link">Logout</a>
                {% else %}
                <a href="{% url 'index_app:register' %}" class="nav-item nav-link">Register</a>
                <a href="{% url 'index_app:login' %}" class="nav-item nav-link">Login</a>
                {% endif %}
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Departments</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="{% url 'course_app:cs' %}" class="dropdown-item">Computer Science</a>
                        <a href="{% url 'course_app:comm' %}" class="dropdown-item">Commerce</a>
                        <a href="{% url 'course_app:bio' %}" class="dropdown-item">Biotech</a>
                        <a href="{% url 'course_app:BE' %}" class="dropdown-item">BE</a>
                        <a href="{% url 'course_app:diploma' %}" class="dropdown-item">Diploma</a>
                    </div>
                </div>

            </div>
            <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
{% block content %}
{% endblock %}
</body>
</html>

FinalTask/templates/bio.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Biotech</title>
</head>
<body>
{% block content %}
    <div class="container-xxl py-5 category">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Categories</h6>
                <h1 class="mb-5">BIOTECH </h1>
            </div>
            <div class="row g-3">
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/bio3.webp' %}" alt="">

                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/bio2.webp' %}" alt="">
                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/' %}" alt="">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.7s" style="min-height: 350px;">
                    <a class="position-relative d-block h-100 overflow-hidden" href="">
                        <img class="img-fluid position-absolute w-100 h-100" src="{% static 'img/bio4.webp' %}" alt="" style="object-fit: cover;">
                    </a>
                </div>
            </div>
        </div>
    </div>
<a href="{% url 'index_app:form' %}" class="btn btn-primary">Register Form</a>
{% endblock %}
</body>
</html>

FinalTask/templates/com.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commerce </title>
</head>
<body>
{% block content %}
    <div class="container-xxl py-5 category">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3"> Course Categories</h6>
                <h1 class="mb-5">COMMERCE DEPARTMENTS</h1>
            </div>
            <div class="row g-3">
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/bcom1.jpg' %}" alt="" width="600" height="500">

                            </a>
                        </div>

                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/comm6.jpg' %}" alt="" width="1300" height="500">

                            </a>

                            </div>

                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/comm2.jpg' %}" alt="">


                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.7s" style="min-height: 350px;">
                    <a class="position-relative d-block h-100 overflow-hidden" href="">
                        <img class="img-fluid position-absolute w-100 h-100" src="{% static 'img/comm8.webp' %}" alt="" style="object-fit: cover;" width="700" height="500">



                    </a>
                </div>
            </div>
        </div>
    </div>

<a href="{% url 'index_app:form' %}" class="btn btn-primary">Register Form</a>
{% endblock %}
</body>
</html>

FinalTask/templates/cs.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Computer Science</title>
</head>
<body>

  <!-- Categories Start -->
{% block content %}
    <div class="container-xxl py-5 category">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3"> Course Categories</h6>
                <h1 class="mb-5">COMPUTER SCIENCE DEPARTMENTS</h1>
            </div>
            <div class="row g-3">
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/cs5.jpg' %}" alt="">

                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/cs.webp' %}" alt="">

                            </a>
                        </div>
                         <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/course-2.jpg' %}" alt="">

                            </a>
                        </div>



                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/cs1.webp' %}" alt="">

                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.7s" style="min-height: 350px;">
                    <a class="position-relative d-block h-100 overflow-hidden" href="">
                        <img class="img-fluid position-absolute w-100 h-100" src="{% static 'img/cs8.jpg' %}" alt="" style="object-fit: co" width="500" height="600">

                    </a>
                </div>
            </div>
        </div>
    </div>


<a href="{% url 'index_app:form' %}" class="btn btn-primary-center">Register Form</a>


{% endblock %}
</body>
</html>

FinalTask/templates/diploma.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DIPLOMA</title>
</head>
<body>
{% block content %}
    <div class="container-xxl py-5 category">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Categories</h6>
                <h1 class="mb-5">DIPLOMA</h1>
            </div>
            <div class="row g-3">
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/diploma3.webp' %}" alt="">

                            </a>
                        </div>
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/diploma2.webp' %}" alt="">

                            </a>
                             <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/diploma4.jpg' %}" alt="">

                            </a>
                        </div>
                            <div class="col">
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                            <a class="position-relative d-block overflow-hidden" href="">
                                <img class="img-fluid" src="{% static 'img/diploma1.jpg' %}" alt="">

                            </a>
                        </div>
                    </div>
                </div>

                <a href="{% url 'index_app:form' %}" class="btn btn-primary-center">Register Form</a>
                {% endblock %}
</body>
</html>

FinalTask/templates/loginpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body style="text-align:center;color:red;background-color:pink;">
<h1><i>Login</i></h1><br><br>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<form action="login" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
    <input type="text" name="username" class="form-control" placeholder="Enter username">
     <input type="password" name="password"  class="form-control" placeholder="Enter your password"><br><br>
    <button class="btn btn-primary">Submit</button>
                       </div>
        </div>
    </div>
    <form>
 </body>
</html>

FinalTask/templates/logoutpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>

</body>
</html>

FinalTask/templates/register form.html
<!DOCTYPE html>
<html>
<head>
  <title>Registration Form</title>


</head>
<body>

  <form action="/submit_registration" method="post">
    <h2>Registration Form</h2>
    <label for="fullname">Full Name:</label>
    <input type="text" id="fullname" name="fullname" required><br>

    <label for="fullname">DOB:</label>
    <input type="date" id="date" name="date" required><br>

    <label for="email">Age:</label>
    <input type="number" id="number" name="number" required><br>

    <label for="phone number">Phone Number:</label>
    <input type="tel" id="number1" name="number" required><br>

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required><br>

    <label for="address">Address:</label>
    <input type="text" id="address" name="address" required><br>

    <label>Gender:</label>
   <input type="radio" name="Gender" value="Male">Male
      <input type="radio" name="Gender" value="Female">Female
      <br>
       <label for="department">Department:</label>
<select id="department" name="department" class="select-input">

      <option  value="computer science">Computer Science</option>

      <option value="computer application">Computer Application</option>

      <option value="commerce">Commerce</option>
      <option value="biotech">Biotech</option>
      <option value="diploma">Diploma</option>

</select>
       <br><br>
    <input type="submit" value="Register">
      <a href="{% url 'final_app:index' %}" class="btn btn-primary">Continue</a>
  </form>

</body>
</html>

FinalTask/templates/registerpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body style="text-align:center;color:blue;background-color:pink;">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h2>REGISTER</h2>
<div class="row">
    <div class="col-md-6 col-sm-8">
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" class="form-control" placeholder="Enter username">
    <input type="password" name="password" class="form-control" placeholder="Enter your password">
    <input type="password" name="password1" class="form-control" placeholder="Enter your confirm password">
<br>
        <button class="btn btn-primary">Submit</button>
</form>
</div>
    </div>
{% for msg in messages %}
{{msg}}
{% endfor %}

</body>
</html>